// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZ4d42ATdWiJx_evrzcx0hZOa8YszKvM',
    appId: '1:1055293695106:web:7951e265931ba99761409b',
    messagingSenderId: '1055293695106',
    projectId: 'noblegroves',
    authDomain: 'noblegroves.firebaseapp.com',
    storageBucket: 'noblegroves.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrRc8gJEQxJC5x9aEhZddOrw_7DeZtK0s',
    appId: '1:1055293695106:android:97ab67c080fe1f6a61409b',
    messagingSenderId: '1055293695106',
    projectId: 'noblegroves',
    storageBucket: 'noblegroves.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAiyfIz_EcglQVxmpOxQuSzAstp5nNuqQ',
    appId: '1:1055293695106:ios:0c533a28b741fb2561409b',
    messagingSenderId: '1055293695106',
    projectId: 'noblegroves',
    storageBucket: 'noblegroves.appspot.com',
    iosBundleId: 'com.example.flutterNoblegroves',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAiyfIz_EcglQVxmpOxQuSzAstp5nNuqQ',
    appId: '1:1055293695106:ios:199560cd59dedf2161409b',
    messagingSenderId: '1055293695106',
    projectId: 'noblegroves',
    storageBucket: 'noblegroves.appspot.com',
    iosBundleId: 'com.example.flutterNoblegroves.RunnerTests',
  );
}
